apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME # this came from docker hub mongo image details page.
          valueFrom:
            secretKeyRef:
              name: mongodb-secret # this came from the metadata defined inside secret file --> mongo-mongoexp-services-configmap-secrets-ingress-k8s-deployment\mongo-secret.yaml
              key: mongo-root-username # this came from mongo-mongoexp-services-configmap-secrets-ingress-k8s-deployment\mongo-secret.yaml where we cretaed the secret with base 64
        - name: MONGO_INITDB_ROOT_PASSWORD # this came from docker hub mongo image details page.
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret # this came from the metadata defined inside secret file --> mongo-mongoexp-services-configmap-secrets-ingress-k8s-deployment\mongo-secret.yaml
              key: mongo-root-password # this came from mongo-mongoexp-services-configmap-secrets-ingress-k8s-deployment\mongo-secret.yaml where we cretaed the secret with base 64
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
